branch-defaults:
  default:
    environment: CollegeSports
    group_suffix: null
global:
  application_name: CollegeSports
  branch: null
  default_ec2_keyname: null
  default_platform: node.js
  default_region: us-east-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
